#### NumPy is a multi-dimensional array library. It can store 1D, 2D, 3D Arrays.
#### NumPy is fast in comparison to lists:
1. Because NumPy uses fixed values i.e. it uses less bytes of memory.
2. No type checking when iterating through array objects in NumPy.
3. It uses contiguous memory.

#### Difference b/w Lists and NumPy:
1. We can apply opeartions on individual elements of NumPy such as addition, multiplication, etc., but cannot apply on lists.

#### Applications of NumPy:
1. Mathematics (MATLAB Replacement)
2. Plotting (Matplotlib)
3. Backend (Pandas, Connect 4, digital Photography)
4. Machine Learning

#### IN ARRAYS:
1. axis = 0  - Rows
2. axis = 1  - Columns

In [177]:
import numpy as np

# The Basics

In [178]:
a = np.array([1,2,3], dtype="int32")
print(a)

[1 2 3]


In [179]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [180]:
# Get Dimensions
print(a.ndim)
print(b.ndim)

1
2


In [181]:
# Get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [182]:
# Get Type
print(a.dtype)
print(b.dtype)

int32
float64


In [183]:
#Get size
a.itemsize

4

In [185]:
# Get Total Size
a.nbytes
    #OR
#a.itemsize * a.size

12

# Accessing/Changing specific elements, rows, columns, etc.

In [186]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [187]:
a.shape

(2, 7)

In [188]:
# Get specific element [row, column]
a[1, 5]
  #OR
a[1, -2]

13

In [189]:
# Get a specific Row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [190]:
# Get a specific Column
a[:, 2]

array([ 3, 10])

In [191]:
# Getting a little more fancy [start_index:end_index:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [192]:
# Changing an element
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [195]:
# Changing a whole column or row
a[:,2] = 5
print(a, "\n")
   #OR
a[1,:] = 3
print(a, "\n")

  #OR
a[1,:] = [8,9,10,11,12,13,14]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]] 

[[1 2 5 4 5 6 7]
 [3 3 3 3 3 3 3]] 

[[ 1  2  5  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


3D Array

In [46]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [48]:
# Get specific element (work outside in)
b[0,1,1]

# And use all above things same here

4

# Initializing Different Types of Arrays

In [52]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
# All 1s matrix
np.ones((2,3,3), dtype="int32")

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [56]:
# Any other number
np.full((2,2), 99)  #np.full((shape), value)

array([[99, 99],
       [99, 99]])

In [58]:
# Any other number (full_like)
# of any shape which is already defined previously
np.full(a.shape, 4)
       #OR
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [196]:
# Random decimal numbers
print(np.random.rand(4,2), "\n")
    #OR
print(np.random.random_sample(a.shape))

[[0.88146628 0.7887163 ]
 [0.5577784  0.30545788]
 [0.15809377 0.14255776]
 [0.3384222  0.3476642 ]] 



array([[0.42818609, 0.57538004, 0.35205998, 0.67908417, 0.47391397,
        0.30699491, 0.82877394],
       [0.40498085, 0.43200559, 0.39601904, 0.64311337, 0.8426436 ,
        0.74936641, 0.86044356]])

In [197]:
# Random integer values
print(np.random.randint(7, size=(3,3)), "\n")   # np.random.randint(start,end, size=(size))
         #OR                                    # By default start starts from 0 if not specifed
print(np.random.randint(4,8, size=(3,3)))

[[4 2 2]
 [0 4 1]
 [6 3 3]] 

[[4 6 7]
 [6 6 7]
 [7 4 5]]


In [71]:
# The Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
# Repeat an Array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)  # np.repeat(arr, no. of times, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [199]:
# IMG 01
# Quiz

output = np.ones((5,5))
print(output, "\n")

z = np.zeros((3,3))
z[1,1] = 9
print(z, "\n")

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be careful when copying Arrays

In [200]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)
print(a, "\n")   # Problem - we haven't copied to a, because b is not making a seperate copy of a, 
                 # instead of using the same address as a to access the values.

# Instead
b = a.copy()
b[0] = 1
print(b)
print(a)

[100   2   3]
[100   2   3] 

[1 2 3]
[100   2   3]


# Mathematics

In [87]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [104]:
print("Addition       : ", a + 2)
print("Subtraction    : ", a - 2)
print("Multiplication : ", a * 2)
print("Division       : ", a / 2)
print("Power          : ", a ** 2)

Addition       :  [3 4 5]
Subtraction    :  [-1  0  1]
Multiplication :  [2 4 6]
Division       :  [0.5 1.  1.5]
Power          :  [1 4 9]


In [103]:
b = np.array([4,5,6])
print("Addition       : ", a + b)
print("Subtraction    : ", a - b)
print("Multiplication : ", a * b)
print("Division       : ", a / b)
print("Power          : ", a ** b)

Addition       :  [5 7 9]
Subtraction    :  [-3 -3 -3]
Multiplication :  [ 4 10 18]
Division       :  [0.25 0.4  0.5 ]
Power          :  [  1  32 729]


In [105]:
# Take sin of all values
np.sin(a)
# and all the others like, cos, tan, cot, etc.

array([0.84147098, 0.90929743, 0.14112001])

# Linear Algebra

### Addind the matrices needs the basic algebra rule:
1. No. of Rows of A = No. Columns of B 
2. No. of Columns of A = No. of Rows of B

In [202]:
a = np.ones((2,3))
print(a, "\n")

b = np.full((3,2), 2)
print(b, "\n")

np.matmul(a,b)  # Matrix Multiplication

[[1. 1. 1.]
 [1. 1. 1.]] 

[[2 2]
 [2 2]
 [2 2]] 



array([[6., 6.],
       [6., 6.]])

In [110]:
# Finding the determinant 
c = np.identity(3)
np.linalg.det(c)   # linalag.det = LinearAlgebra.Determinant

1.0

### We can perform all sorts of Linear Algebra functions also.

# Statistics

In [111]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [203]:
print(np.min(stats), "\n")
      #OR
print(np.min(stats, axis=1), "\n") # axis=1 - Both Rows, Min from both the rows

print(np.max(stats), "\n")
     #OR
print(np.max(stats, axis=1))

1 

[1 4] 

6 

[3 6]


In [122]:
print(np.sum(stats))
   #OR
print(np.sum(stats, axis=0))

21
[5 7 9]


# Reorganizing Arrays 

In [128]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print("\n",after)

[[1 2 3 4]
 [5 6 7 8]]

 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [127]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2]))
        #OR
print("\n", np.vstack([v1,v2,v2,v2]))

[[1 2 3 4]
 [5 6 7 8]]

 [[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


In [131]:
# Horozontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1, "\n", h2, "\n")

print(np.hstack((h1,h2)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 [[0. 0.]
 [0. 0.]] 

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


# Miscellaneous

### Load data from file

In [167]:
filedata = np.genfromtxt('data.txt', delimiter =',')
print(filedata, "\n")
     #OR
filedata = filedata.astype('int32')
print(filedata)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24.] 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


### Boolean Masking and Advanced Indexing

In [157]:
filedata > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [168]:
filedata[filedata > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [159]:
# You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[[1,2,8]])   # Prints the elements on this specific indexes

[2 3 9]


In [162]:
print(np.any(filedata > 5, axis = 0))  #Checks row wise
            #OR
print(np.all(filedata > 5, axis = 0))  #Checks row wise

True
False


In [171]:
print((filedata > 5) & (filedata < 10))
            #OR
print("\n", ~((filedata > 5) & (filedata < 10)))  # Reverse

[False False False False False  True  True  True  True False False False
 False False False False False False False False False False False False]

 [ True  True  True  True  True False False False False  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True]


# -------------------------The End-----------------------------